FROM    centos:centos6

RUN     rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
RUN     sudo apt-get install -y nodejs

COPY . /src
RUN cd /src; npm install

EXPOSE  3000
CMD ["node", "/src/app.js"]
